
--CandidateDocuments

INSERT INTO [Interview].[dbo].[CandidateDocuments] ([Surname], [Name], [Patronymic], [Phonenumber], [Email], [CV], [Address]) VALUES (N'Candidate_Surname1', N'Candidate_Name1', N'Candidate_Patronymic1', N'Candidate_PhoneNumber1', N'Candidate_Email1@mail.com', N'http://example.com/cv-files/Candidate_1.pdf', N'Candidate_Address1');
INSERT INTO [Interview].[dbo].[CandidateDocuments] ([Surname], [Name], [Patronymic], [Phonenumber], [Email], [CV], [Address]) VALUES (N'Candidate_Surname2', N'Candidate_Name2', N'Candidate_Patronymic2', N'Candidate_PhoneNumber2', N'Candidate_Email2@mail.com', N'http://example.com/cv-files/Candidate_1.pdf', N'Candidate_Address2');

--Candidates

INSERT [Interview].[dbo].[Candidates] ([CandidateDocumentId]) VALUES (1)

--Categories

INSERT [Interview].[dbo].[Categories] ([Name]) VALUES ( N'Category_1')
INSERT [Interview].[dbo].[Categories] ([Name]) VALUES ( N'Category_2')

--Levels

INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'easy', CAST(0.25 AS Decimal(18, 2)))
INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'medium', CAST(0.50 AS Decimal(18, 2)))
INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'hard', CAST(1.00 AS Decimal(18, 2)))

--StructureTypes

INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Department')
INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Branch')
INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Subsection')

--Structures

INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_1', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Branch_1', N'1', 2)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_1', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_1.2', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Branch_2', N'1', 2)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_2.1', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_2.2', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_2', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_3', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_4', N'0', 1)

--Positions

INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Junior')
INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Middle')
INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Senior')

--Vacancies

INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_1', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 1, 1)
INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_2', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 2, 1)
INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_3', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 3, 1)

--Questions

INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_1', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_2', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_3', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_4', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_5', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_6', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_7', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_8', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_9', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_10', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_11', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_12', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_13', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_14', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_15', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_16', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_17', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_18', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_19', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_20', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_21', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_22', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_23', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_24', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_25', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_26', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_27', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_28', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_29', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_30', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_31', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_32', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_33', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_34', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_35', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_36', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_37', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_38', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_39', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_40', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_41', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_42', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_43', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_44', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_45', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_46', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_47', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_48', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_49', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_50', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_51', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_52', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_53', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_54', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_55', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_56', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_57', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_58', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_59', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_60', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_61', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_62', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_63', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_64', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_65', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_66', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_67', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_68', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_69', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_70', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_71', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_72', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_73', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_74', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_75', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_76', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_77', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_78', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_79', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_80', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_81', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_82', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_83', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_84', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_85', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_86', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_87', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_88', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_89', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_90', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_91', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_92', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_93', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_94', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_95', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_96', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_97', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_98', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_99', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_100', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_101', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_102', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_103', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_104', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_105', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_106', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_107', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_108', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_109', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_110', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_111', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_112', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_113', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_114', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_115', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_116', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_117', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_118', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_119', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_120', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_121', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_122', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_123', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_124', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_125', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_126', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_127', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_128', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_129', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_130', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_131', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_132', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_133', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_134', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_135', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_136', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_137', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_138', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_139', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_140', 1, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_141', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_142', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_143', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_144', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_145', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_146', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_147', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_148', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_149', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_150', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_151', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_152', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_153', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_154', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_155', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_156', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_157', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_158', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_159', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_160', 1, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_161', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_162', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_163', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_164', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_165', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_166', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_167', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_168', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_169', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_170', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_171', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_172', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_173', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_174', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_175', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_176', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_177', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_178', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_179', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_180', 2, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_181', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_182', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_183', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_184', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_185', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_186', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_187', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_188', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_189', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_190', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_191', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_192', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_193', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_194', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_195', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_196', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_197', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_198', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_199', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_200', 2, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_201', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_202', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_203', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_204', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_205', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_206', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_207', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_208', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_209', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_210', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_211', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_212', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_213', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_214', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_215', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_216', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_217', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_218', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_219', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_220', 3, 1, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_221', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_222', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_223', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_224', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_225', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_226', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_227', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_228', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_229', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_230', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_231', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_232', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_233', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_234', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_235', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_236', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_237', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_238', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_239', 3, 2, 8)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_240', 3, 2, 8)
