--Positions

INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Junior')
INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Middle')
INSERT [Interview].[dbo].[Positions] ([Name]) VALUES (N'Senior')

--Vacancies

INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_1', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 1, 1)
INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_2', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 2, 1)
INSERT [Interview].[dbo].[Vacancies] ( [Title], [Description], [StartDate], [EndDate], [PositionId], [StructureId]) VALUES ( N'Vacancy_3', N'Vacancy_Description', CAST(N'2024-07-29T17:20:42.0630000' AS DateTime2), CAST(N'2024-08-29T17:20:42.0630000' AS DateTime2), 3, 1)

--CandidateDocuments

INSERT INTO [Interview].[dbo].[CandidateDocuments] ([Surname], [Name], [Patronymic], [Phonenumber], [Email], [CV], [Address]) VALUES (N'Candidate_Surname', N'Candidate_Name', N'Candidate_Patronymic', N'Candidate_PhoneNumber', N'Candidate_Email@mail.com', N'http://example.com/cv-files/Candidate_1.pdf', N'Candidate_Address');

--Candidates

INSERT [Interview].[dbo].[Candidates] ([CandidateDocumentId]) VALUES (1)

--Categories

INSERT [Interview].[dbo].[Categories] ([Name]) VALUES ( N'Category_1')
INSERT [Interview].[dbo].[Categories] ([Name]) VALUES ( N'Category_2')

--Levels

INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'easy', CAST(0.25 AS Decimal(18, 2)))
INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'medium', CAST(0.50 AS Decimal(18, 2)))
INSERT [Interview].[dbo].[Levels] ([Name], [Coefficient]) VALUES (N'hard', CAST(1.00 AS Decimal(18, 2)))

--StructureTypes

INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Department')
INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Branch')
INSERT [Interview].[dbo].[StructureTypes] ([Name]) VALUES (N'Subsection')

--Structures

INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_1', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Branch_1', N'1', 2)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_1', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_1.2', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Branch_2', N'1', 2)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_2.1', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Subsection_2.2', N'2', 3)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_2', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_3', N'0', 1)
INSERT [Interview].[dbo].[Structures] ([Name], [ParentId], [StructureTypeId]) VALUES (N'Department_4', N'0', 1)

--Questions

INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_1', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_2', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_3', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_4', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_5', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_6', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_7', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_8', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_9', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_10', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_11', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_12', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_13', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_14', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_15', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_16', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_17', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_18', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_19', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_20', 1, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_21', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_22', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_23', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_24', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_25', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_26', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_27', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_28', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_29', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_30', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_31', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_32', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_33', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_34', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_35', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_36', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_37', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_38', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_39', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_40', 1, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_41', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_42', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_43', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_44', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_45', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_46', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_47', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_48', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_49', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_50', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_51', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_52', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_53', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_54', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_55', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_56', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_57', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_58', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_59', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_60', 2, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_61', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_62', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_63', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_64', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_65', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_66', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_67', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_68', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_69', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_70', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_71', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_72', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_73', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_74', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_75', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_76', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_77', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_78', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_79', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_80', 2, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_81', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_82', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_83', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_84', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_85', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_86', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_87', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_88', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_89', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_90', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_91', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_92', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_93', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_94', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_95', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_96', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_97', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_98', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_99', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_100', 3, 1, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_101', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_102', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_103', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_104', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_105', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_106', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_107', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_108', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_109', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_110', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_111', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_112', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_113', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_114', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_115', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_116', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_117', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_118', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_119', 3, 2, 1)
INSERT [Interview].[dbo].[Questions] ([Text], [LevelId], [CategoryId], [StructureId]) VALUES (N'Question_120', 3, 2, 1)
