version: '3.4'

services:
  interview.api:
    image: ${DOCKER_REGISTRY-}interviewapi
    build:
      context: .
      dockerfile: Presentation/Interview.API/Dockerfile
    ports:
      - "50000:80"
      - "50005:443"
    # environment:
    #   - TZ=Asia/Baku
    # extra_hosts:
    #    - "host.docker.internal:192.168.22.6"
    #    - "host.docker.internal:192.168.22.189"



