version: '3.4'

services:
  interview.api:
    image: ${DOCKER_REGISTRY-}interviewapi
    build:
      context: .
      dockerfile: Presentation/Interview.API/Dockerfile
    ports:
      - "50000:80"
      - "50005:443"
    # environment:
    # - ASPNETCORE_ENVIRONMENT=Docker
